apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}  
  labels: 
    app: {{ .Values.deployment.labels.appName }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.labels.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.labels.appName }}
    spec:
      terminationGracePeriodSeconds: 60
      containers:
          - name: {{ .Values.deployment.container.name }}
            image: {{ .Values.deployment.container.image.name }}:{{ .Values.deployment.container.image.version }}
            imagePullPolicy: {{ .Values.deployment.container.image.imagePullPolicy }}
            ports:
                - containerPort: {{ .Values.deployment.container.port }}
            env:
                - name: POSTGRES_USER
                  value: {{ .Values.deployment.container.env.postgres_user }}
                - name: POSTGRES_PASSWORD
                  value: {{ .Values.deployment.container.env.postgres_password }}
                - name: POSTGRES_DB
                  value: {{ .Values.deployment.container.env.name_of_db }}
            resources:
                requests:
                    cpu: {{ .Values.deployment.container.resources.requests.cpu }}
                    memory: {{ .Values.deployment.container.resources.requests.memory }}
                limits:
                    cpu: {{ .Values.deployment.container.resources.limits.cpu }}
                    memory: {{ .Values.deployment.container.resources.limits.memory }}