apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.deployment.labels.appName }}

spec:
  replicas: {{ .Values.deployment.replicas }}

  selector:
    matchLabels:
      app: {{ .Values.deployment.labels.appName }}

  template:
    metadata:
      labels:
        app: {{ .Values.deployment.labels.appName }}

    spec:
      terminationGracePeriodSeconds: 60

      containers:
        - name: {{ .Values.deployment.container.name }}

          image: >-
            {{ .Values.deployment.container.image.name }}:
            {{- .Values.deployment.container.image.version }}

          imagePullPolicy: >-
            {{ .Values.deployment.container.image.imagePullPolicy }}

          {{- if .Values.secretEnv.enabled }}
          envFrom:
            - secretRef:
                name: {{ .Values.secretEnv.name }}
          {{- end }}

          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}

          ports:
            - name: http
              containerPort: {{ .Values.deployment.container.port }}
              protocol: TCP

          startupProbe:
            httpGet:
              path: /livez
              port: http
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /livez
              port: http
            periodSeconds: 15
            timeoutSeconds: 2
            failureThreshold: 3

          resources:
            requests:
              cpu: {{ .Values.deployment.container.resources.requests.cpu }}
              memory: {{ .Values.deployment.container.resources.requests.memory }}

            limits:
              cpu: {{ .Values.deployment.container.resources.limits.cpu }}
              memory: {{ .Values.deployment.container.resources.limits.memory }}