apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.deployment.labels.appName }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.deployment.labels.appName }}
  ports:
    - name: {{ .Values.service.Map_ports.name }}   
      protocol: TCP
      port: {{ .Values.service.Map_ports.port }}
      targetPort: {{ .Values.service.Map_ports.targetPort }}
