apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}

  labels:
    app: {{ .Values.deployment.labels.appName }}

spec:
  type: {{ .Values.service.type }}

  selector:
    app: {{ .Values.deployment.labels.appName }}

  ports:
    - name: mcp
      protocol: TCP
      port: {{ .Values.service.ports.mcp.port }}
      targetPort: mcp

    - name: metrics
      protocol: TCP
      port: {{ .Values.service.ports.metrics.port }}
      targetPort: metrics